spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate.dialect: org.hibernate.dialect.DerbyTenSevenDialect
  datasource:
    url: jdbc:derby:derby-application-db;create=true;
    username: sa
    password: sa
    hikari:
      maximum-pool-size: 5
      driver-class-name: org.apache.derby.jdbc.EmbeddedDriver
    driver-class-name: org.apache.derby.jdbc.EmbeddedDriver
  liquibase:
    change-log: classpath:/db/changelog/db.changelog.xml
    enabled: true

server:
  port: 8090
  servlet:
    context-path: /api

management:
  endpoints:
    enabled-by-default: true
    web:
      base-path: /management
      exposure:
        include: info,health,prometheus,liquibase,beans,mappings
  endpoint:
    prometheus:
      enabled: true
    info:
      enabled: true
    health:
      enabled: true
      time-to-live: 10000
  server:
    port: 8190
    servlet:
      context-path: /
  livenessProbe:
    initialDelaySeconds: 180
  security:
    enabled: false